# Generated by Django 4.2.5 on 2023-09-15 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_image1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_image2',
        ),
        migrations.AddField(
            model_name='store',
            name='contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='installation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='owner_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='purchase_data',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
