# Generated by Django 4.2.5 on 2023-09-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0002_remove_store_store_image1_remove_store_store_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
