# Generated by Django 4.2.5 on 2023-09-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0004_tasksubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
        migrations.AddField(
            model_name='store',
            name='brands',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sales',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='shop_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner_name',
            field=models.CharField(max_length=255),
        ),
    ]
