# Generated by Django 4.2.5 on 2023-09-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0007_alter_storecontact_store_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storecontact',
            old_name='store_id',
            new_name='store',
        ),
    ]
