# Generated by Django 4.2.5 on 2023-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0008_rename_store_id_storecontact_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='store_contacts', to='mystoreapp.storecontact'),
        ),
    ]
