# Generated by Django 4.2.5 on 2023-11-23 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0014_project_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_store', to='mystoreapp.store'),
        ),
    ]
