# Generated by Django 4.2.5 on 2023-11-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0017_remove_tasksubmission_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='store_contact', to='mystoreapp.storecontact'),
        ),
    ]
