# Generated by Django 4.2.5 on 2023-11-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0018_alter_store_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='storecontact', to='mystoreapp.storecontact'),
        ),
    ]
