# Generated by Django 4.2.5 on 2023-11-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0021_storecontacts_store_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='StoreContacts',
        ),
    ]
