# Generated by Django 4.2.5 on 2023-11-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0022_remove_store_contacts_delete_storecontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='mystoreapp.store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='storecontacts', to='mystoreapp.storecontacts'),
        ),
    ]
