# Generated by Django 4.2.5 on 2023-11-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0023_storecontacts_store_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreContacts',
            new_name='StoreContact',
        ),
    ]
