# Generated by Django 4.2.5 on 2023-11-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0025_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionimages',
            name='status',
        ),
        migrations.RemoveField(
            model_name='submissionimages',
            name='submission_feedback',
        ),
        migrations.AlterField(
            model_name='submissionimages',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
