# Generated by Django 4.2.5 on 2023-11-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0026_remove_submissionimages_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionimages',
            name='user',
        ),
    ]
