# Generated by Django 4.2.5 on 2023-12-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0030_assignedpermission_assignee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedpermission',
            old_name='assignee_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='assignedpermission',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='assignedpermission',
            old_name='user_id',
            new_name='use',
        ),
    ]
