# Generated by Django 4.2.5 on 2023-12-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0032_rename_use_assignedpermission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionimages',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
