# Generated by Django 4.2.5 on 2024-01-09 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0034_userattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattribute',
            name='city',
        ),
        migrations.AddField(
            model_name='userattribute',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mystoreapp.district'),
        ),
    ]
